language: php

php:
- 7.0
- 7.1
- 7.2

before_script:
- composer self-update
- composer install --dev

script:
  # Check the standards
  - ./vendor/bin/phpcs --standard=PSR2 --colors src
  # Tests
  - cp tests/.env.sample tests/.env
  - ./vendor/bin/phpunit tests
